

name: BeerCamp at SXSW 2011

# - name: 
#   player1: 
#   player2: 
#   player3: 
#   player4: 
#   player5: 
#   player1_twitter: 
#   player2_twitter: 
#   player3_twitter:

team_pairs:
  - group: Division A
    team_a:
      name: nclud One
      player1: Martin Ringlein
      player2: Alex Giron
      player3: Lauren Moon
      player4: Brandon Jones
      player5: Brian Singer
      player1_twitter: martymadrid
      player2_twitter: alexgiron
      player3_twitter: laurenmoon
      
    team_b:
      name: Nclud 2 For Realz. Hide Yo Kids. Hide Yo Wife
      player1: Tom Gianttassio
      player2: David DeSandro
      player3: Dan Drinkard
      player4: Doris Steere
      player5: Michael Dick
      player2_twitter: desandro

  - group: Division B
    team_a :
      name: YayQuery Sparkle Force
      player1: Commodore General Alex Sexton
      player2: Brigadier 1st Class Adam J. Sontag
      player3: Paul Irish
      player4: Rebecca Murphey
      player5: John Resig in spirit
      player1_twitter: slexaxton
      player2_twitter: ajpiano
      player3_twitter: paul_irish

    team_b:
      name: Hanerinoids
      player1: Patrick Haney
      player2: Jenna Marino
      player3: John Doe
      player4: Jane Doe
      player5: Jacob D'oh!
      player1_twitter: notasausage
      player2_twitter: jennamarino

  - group: Waitlist
    team_a:
      name: The cast of Blindness
      player1: Mark Ruffalo
      player2: Julianne Moore
      player3: Danny Glover
      player4: Gael García Bernal
      player5: Don McKellar
      player2_twitter: twitter

