
name: BeerCamp at SXSW 2011

teams:
  
  - name: 2 girls, 3 guys and a cup.
    players:
      - name: Kerry Gunther
        twitter: kerrygunther
      - name: Jim Basio
      - name: Tanya Bodnya
      - name: Dario Tadic
      - name: Nastya Loskutova
  
  - name: The Irish Hooters
    players:
      - name: Patrick Haney
        twitter: notasausage
      - name: J Cornelius
        twitter: jc
      - name: Matt Downey
        twitter: mattdowney
      - name: Jenna Marino
        twitter: jennamarino
      - name: Adam Little
        twitter: adam_little
  
  - name: Just the Flip
    players:
      - name: Rusty Walters
        twitter: russwalters
      - name: Kim Richie
        twitter: kimberwom
      - name:   Ken Peluso
      - name: Dave Wassell
      - name: Cara Citino
  
  - name: Kickstarter
    players:
      - name: Andrew Cornett
        twitter: amotion
      - name: Samuel Cole
        twitter: samuelcole
      - name: Fred Benenson
        twitter: mecredis
      - name: Charles Adler
        twitter: cadler
      - name: Brett Camper
        twitter: professorlemeza



  
# - name: TEAMNAME
#   players:
#     - name: PLAYER1
#       twitter: TWITTER1
#     - name: PLAYER2
#       twitter: TWITTER2
#     - name: PLAYER3
#       twitter: TWITTER3
#     - name: PLAYER4
#       twitter: TWITTER4
#     - name: PLAYER5
#       twitter: TWITTER5
  
