
name: BeerCamp at SXSW 2011

teams:
  
  - name: '2 girls, 3 guys and a cup.'
    players:
      - name: Kerry Gunther
        twitter: kerrygunther
      - name: Jim Basio
      - name: Tanya Bodnya
      - name: Dario Tadic
      - name: Nastya Loskutova
  
  - name: The Irish Hooters
    players:
      - name: Patrick Haney
        twitter: notasausage
      - name: J Cornelius
        twitter: jc
      - name: Matt Downey
        twitter: mattdowney
      - name: Jenna Marino
        twitter: jennamarino
      - name: Adam Little
        twitter: adam_little
  
  - name: Just the Flip
    players:
      - name: Rusty Walters
        twitter: russwalters
      - name: Kim Richie
        twitter: kimberwom
      - name:   Ken Peluso
      - name: Dave Wassell
      - name: Cara Citino
  
  - name: Kickstarter
    players:
      - name: Andrew Cornett
        twitter: amotion
      - name: Samuel Cole
        twitter: samuelcole
      - name: Fred Benenson
        twitter: mecredis
      - name: Charles Adler
        twitter: cadler
      - name: Brett Camper
        twitter: professorlemeza

  - name: GSP
    players:
      - name: Mike Geiger
        twitter: tastytruth
      - name: Carey Head
        twitter: fourminutesong
      - name: Mike Davidson
        twitter: davidsonmike
      - name: Derek Richmond
        twitter: designagnostic
      - name: Peter Albrycht
  
  - name: London calling
    players:
      - name: Charlie Osmond
        twitter: cosmond
      - name: Alliott Cole
        twitter: alliott
      - name: Ben Barnes
      - name: Pete Cherry
      - name: Jacob Kestner
        twitter: jacobkestner
  
  - name: Team What?!?
    players:
      - name: John Zulim
      - name: Michael McCollough
      - name: Eric Josselyn
      - name: Justin Fae
      - name: Chang Cho

  - name: Loch Ness
    players:
      - name: Rob Sternenberg
        twitter: foodtrailersatx
      - name: Tony Yamanaka
      - name: Christina Conklin
      - name: Darrin Jensen
      - name: Jason Gray
  
  - name: Das Boots
    players:
      - name: Juan Moran
      - name: Ralf Garcia
      - name: Remington Ruiz
      - name: Tyler McEwen
      - name: Jason Fialkoff
  
  - name: Cinco Trouble
    players:
      - name: Sandra Fabian
        twitter: sanfab44
      - name: Jesse Ramirez
      - name: Charles Williams
      - name: Amy Zamora
      - name: Gina Romero
  
  - name: Who's cider you on?
    players:
      - name: Ian Ochiltree
        twitter: ianochiltree
      - name: Ally Stuart
        twitter: EtAlly
      - name: Matt Golding
        twitter: mattgolding
      - name: Chris Quigley
        twitter: rubber_republic
      - name: Alex Pitkin
        twitter: Pitkin
  
  - name: Beadenomics
    players:
      - name: Brian Cmiel
        twitter: Fat_Brian
      - name: Rickey Brown
        twitter: Dokopuffs
      - name: Derek Knechtel
      - name: Dana Beristain
      - name: Anthony Thai
  
  - name: Martin&rsquo;s Mom
    players:
      - name: Kevin Smith
        twitter: ksmith
      - name: Greg Robleto
        twitter: robleto
      - name: Doug Dosberg
        twitter: dosberg
      - name: Patrick Woods
        twitter: hakjoon
      - name: Justin S.
        twitter: joeks
  
  # - name: TEAMNAME
  #   players:
  #     - name: PLAYER1
  #       twitter: TWITTER1
  #     - name: PLAYER2
  #       twitter: TWITTER2
  #     - name: PLAYER3
  #       twitter: TWITTER3
  #     - name: PLAYER4
  #       twitter: TWITTER4
  #     - name: PLAYER5
  #       twitter: TWITTER5
  
